apiVersion: v1
kind: Pod
metadata:
  name: ledger-health-check
  namespace: payments
spec:
  restartPolicy: Never
  automountServiceAccountToken: false

  securityContext:
    seccompProfile:
      type: RuntimeDefault

  containers:
    - name: health-check
      image: curlimages/curl:8.11.1

      command:
        - curl
        - -fsS
        - --max-time
        - "10"
        - -H
        - "Host: ledger.local"
        - http://ingress-nginx-controller.ingress-nginx.svc.cluster.local/health-invalid
        #- http://10.96.32.34/health

      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
