---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgC71sO3vgWKpkkC7w6cCnxRwz63wgFcEKlJrrxhc/CuYCyZo0llLvut6kRWdYYJmCMwBWRwjIHwO68Gdaq9XSvOZ0XIXDzk77Qkp1jwdFMGJmMGXSZtiVSdcd3fegABAb2OxXgHAgV+e7T738trMirDN08L6XNuuhUqVxw+/g8RxQAr7xmMs9HnOKcyDZSaus5YlQeR/h+zfMLyK7pFu0pGkdPJJMmV8TN8c/qEWr7IbKT5s11JPDciGn+xjAHBMtqcYhK0LacUD7UQPPeZBisriThMCmYwPmsjeQ6kMAMRaubp9Kl4QRrHYbaytHUi0Lm3k+9qWgA8EUnqnV6B8z9wJNImS7VkF2sKQ/AK4zLJV2GW4tlEiygo9HMzv9ZcciAjlYDbSSwWFS3CXPvkgFxzQQt0/Wm+z3aykzYhnAUK/IcxtjiZMJMYmJ51V2xPncHTPGxmc5pwmdSVBclxosIkFFyE+6SOzpk6ab3Q8CkLeqc9JhJJ2f10cg70IzNa8y8OGSfugTN+2WEA+HK6aNmd+/dT7TjJeYJVcgMZklRUNNpQsxB/Mx4oRv5luSHH1JgiERv+zXwpZflhw1xM2VW20J5YmgrlBUoWpIxrWu47KE07RZx44J1S3JNf4PdVZaXmTJDgQfXJklGM6GpbGipQxRwwScdrBbnPCMwmrzBC9QDOEUTwCS3WWqzDhXsSwcAS6kGJdc3ysUgv8g==
    STRIPE_API_KEY: AgCvU6IIFCTLZ6FX62p9XMHpGxYrrkZJEuq8fXtPiP6LlYULhwbl/jvI4s9s6woV2LREY3bidNR0mFw7jG+NEXjdVThTYgSkDmmSQuHvSlTVtmBFD5OW2osGM7cR65CNC4myCz1qmOj6fRt+PcRN00uTDXvwqRGDTEceViW1YWx2MfuGi6o33l7jh4y7nZoQZlk4gX0H57fR3V9UKU8uIbodZv5Wd+lu2d8k0srCuZmw7XBeyM0BjDYSpRkyZMQYzczap7qtuhkIn+2jBHqVP6EE2OHflqM8Ixhrxl7UnC+lC1I0Ak7Fox0iLVN2UBvaD9rJSYRW8bInUSsUr+tFrXqQLlDVF9/IbgrhpmL6F6Kw30n+pCHKYmioUazFKTcuweHp6tM+AfdmcndvTGPFMZh3WIdOxUtTmvmMM7AebuPVBPnBX26jgxDQmltVc6iuGJQEb16UCe7P4QFMSAqXoWntfr4mwkhEqX3hQbqycKfie/MK0GW1FmcwQWPs5U1vUCL4NtvQKo2LtznH0Lta+AxBeqaNjk+cZXnJ4Kpg8vvUnL4fXqYK5OIZJ1NSUhopP942qfVA0JX6PuMPV+hahLzOjZ0pk4Kdos3O9fpAiZbDfxlA0ycTZMUuarDo0tBOzMELktc9DfTtPRcoh6RP2B4G/7kWjVFZ+mTD1ddIpvDp2mTH09JMJxiPJbLeXCyPA1CB+5swTAcbbTtCQff+iKmMaqmITjTL34jejXGfgw==
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secrets
      namespace: payments
    type: Opaque
