---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgAgc0dSGdcSZSzAm+y+vfXAFtxW/hQHs7yRQ+rU4/UwSrDABXGokhJUG9uLqR8Zhm/Ai5TzCFaKkPBhdN9dxkSJ+T7POBLlQYo08Y2YuY71IYwxLsinNf7c7mT4EKGolKevCX33I+pTYL55cxr9h8yBPJyGRpET1e6Pk/ftnk8+XdrtG2FnaP6DczwE9NucsTkTq934e/QLZg8QombjIhPGlrVGURfpLg+ThhnHJAI4tT+azbm3Mak0QYnGSZqcKn04yJ5eJNWpHo9QkPnV+vkD5C8+oCrtUn6hsmCsxx/cL/WSBe4QElIqY5LC2XNY1CdwWHsJsE8s3xyIA5Y7oBonpUgLH3DIuPMLPVUjWphr/DX15vSG3wbLT3zY49P7FNs7fQQfioazgImxh1cZrJr9rSnTjFZKV1kwfRjK3GG5CHV/tqoLUZz8NjjPg93nmMZv5O4H4LMZC3vK3oVYubgr7dftO2xPlqPosR0WhP7wyKy20vGXNjKrSRmLk6zx4UwJksRxpxnuJjm8rYle2TogaY/sfvcb1sim2tzhPV1QfixJE5Y9nIy+Cwtb/Vh6aslDdU+YmPfw3dwkJhuHttsCmzu5ASBx9Toly1JcvGw1WdYqdEJ1sDLV7zXTaIFf4IJFI35aGz37V4jvnUEWUDhD+scFPEES1oHWRd2UvCrWOs5K/g1w7ys20DTnX8PD43TTPfeVe5dc6kKw7w==
    STRIPE_API_KEY: AgAiEM+J7F8zeILe62UcYyg5zjCSxneeSV+7cR4NhOkAqKsw+laZL2SvK9G2ck4FxUd8FlDbTKXrqe27FqijiJcSyTe3xiVEO/W7UGHnrW2lYTSKJvW8ZsyP0QrEaZNCdOeTUfKpVEX0keAyH1QBGhi9t5ecbWthXwj9MxIGOHmRPLgdGbEz9ZjDVtDxqQob0v11UMALUGR2PHAOa+qBqUkgRcEFiXZFDxGs0YcUmhoRfQjuGrd9wPR2jWIQwu42MSOhD4RIrHj4EqJ+zWYX73wsfN9GgCbWr0s7Ci1kUPrGuJZQURAbmVCWQT7jss2asPg18zWIJro1JzXLssmTBYScugzRUIYtVHxW8q6K9BIkwIsyZeyir6F4I5id8DvYUCWdL2kVu0Cn1oXE+vVrxXtk05lIztRTK5cYgRNnOMLd/lmISXM+/fqmqN48agDOIgbHcfrgP7y6+4ot3igU0VLcnYYm9n3lACTH/ErH2fBRhEeNH65Wxb/STaqeGST7vFOywfqcEQZdyrTDLxJOBXkpVT62yXWCRghBHoIH33FGl9eNrkHAmDBQ6Saz6cjJF3t0R31rUwWQipiFDoqfumz+O1bXVxyPCDWBsVKcuVnJyf2BLKs+LOaNOnKj7hZ/N+i7yMRRITu9NIVlsvqm2XkveWLUW6IsS4dNybisJjBfVfmWAn5g8wgAba4AGmp3Xcw0DjMsF9hGCFpjfo4s5m5hf7CEwSjEzzIjAz7ZZw==
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secrets
      namespace: payments
    type: Opaque
