---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgC9p8tIRCIdAHyF8ZgIciXeakbkNUH48PT2TASX1yfyHG26rMQZuz8go+mxFYYX3s8wZB8+r0TjM2vjAXvRNgynkrk3Paxm+fRCiHhhRQVTt9NF14nrJc592r7rmifJi0XLOEoqzqVdyr971STeiNNXhtItoKrjnCdkbcOhgvGO/VfX+i8iRz7u8ytyxujzr7LOpIKV71p/TJBtThhGc1ZtRTMG2DKs4Y9D1tMk9/wqMmalTUzlC+Sp0CGGo8Dti7/DYbQEnOV4I/BaxAqOQmtZQ5xSUwL9/1ghZDQwlYYXFt1AWMZhEuRoilysm1lgAFXwid3BqPF624af0EZabpscry0khAFecQjBcHZFt2vPSXABep/x44g0M+26GQLfJFGUkj42zla60ezixD52aFUAtXttv6+bdnptmteSva36+Sd9p1IaaKhqzw2im7u3TQYXfHZSUGMucL+wOYklTsS+RD21MM70WTMusXb0yL4+DTdMLVQ59eUcMGtEYm9sQ6MPyZYz7O7OB6iC7+wRnMAdBjtI97iJzffiS3F4sMSNH4GVe6OUZw3u0U7Up+D6Sno26qs/7rjyoZMKLTl7bihPSByiJDM4uBSVo6Om/iSAEuHzJTGIrr3yZLPCsjzReiL9Nlm4pBP0blMiV5szn8f99H/jcFDP53jG5QT10gB+KsZdXHDHiawMtAGlE6wyc4Lbsr6DpxqoPQmjig==
    STRIPE_API_KEY: AgAUbxyFPH691fbzMslo6+ufCaFo5v7lNwKe5k02YAErWNwd30igq3WIBLwWcVdBUdlbz56h9y22YGIQH5frAkaoYsFJxixCTT4z7o+9gvhn7OXaafmXG+vPYYLPQc0cw07luw+hUaLUwiT74UpSY/H9tmoLORkyNc9P/+G9d4o3XneHZuQO/VkyxAKSD9vkJtp8j1O+EBFuHZA53pUinPtTdbPkPOBRHvqyXZQgcBqeevZcjezycEAnmNKq+9EyEChORZ3siUaS7wTI2E+VnKQpm69ac4TcgvhfR6DHjOiKE8h6gHVH4+Vo7l3sQQHft7txDaduUSaccA1JguZTimDRASuRscophN0VCcA9UOqkE/YdAx1QRTpSR7+4uYOBzqQ/7+9bfBINa/iftOvWMMdvGW/lmmBcfgy/SkYD5CW/k4CuKLEx0ctK79QeHsp0I7jIqxg8B7JUNKQIxsRh0boxGuBKnBqmPdYwIpdEl6y1SuSR8XvJw8+xvjp9PHovp1w+pZf3qBw2wPjVsLgDuDY1tjBkg26pccGqvTv/ZxZei1G2xCSmQkK9USZsCMb4Rz++l+5dPKzKUEGlzYRGQHdGI7XIyXmghxMcX/QPVubtdlrtm9z3uN0OkPlagevZC0nNoHBEEqUAUaMspc04oJjP+FH6lmlLoHa/ywM19vWdjhWYyPBw/ARw+HOuiUeoPChwolhQmQxUaQ7BCuYv4e2v3PRuYm8Ow1KwyP9eFg==
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secrets
      namespace: payments
    type: Opaque
