---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgDJzRQsWgM73A7rj2C4YE/QHce1C+Cx0DIPRNpVgGGshC+VaMbPg2I71DyzrH1Wu5cScr6ld38EXYrLRQJBw25QileWt8PGVmL2H9j/vrrgnSv4gtUPhnjyDyQMS3KcgogeRyIwj941LTtq5XqeRJhLnz0fSmGyPwZaXPqNGxcB0ZLAX4JZqCA3q01dagI9NwOBeXwF6KEZiQX3C279zcA2IxYXQqLGIAP+Z1yPBDKL289U1h7FmSTuv1/AA7aaqbx7ybUM55eHiya47AyDH/BbR90LUqw0tWQyL51+RTV6dIfrH06WmmOZXOr6p5tJA85Lj9l+X7EWYLpGo10Kklv2PwxePrE3gp1Zq33LWfZ8mLu0a+VN/gDTUAKf9Fg/KwfePdXkjO/mNVs6mlAKVLjosV4kqVRbUUrKeniUo341AdnrDqPW6BIYs9Ti9TTnynVIsuC4mdrk67CAYQV6bIeVJtsyfSgKkxOuICweDTBcAKttOrrHGRS6eR9SP3ASc5r/w/IX77bkQTJxy2LzuWSDQ49KlImg3r2olqMJtJ+q46owAa2LoUCDHu2SBGpJZCcXojUIkcEGYfXIRnCP6d3v3o3dOTEbT2gYCbUDslaayL0sAkr/Hp5DzrnIzOYjO8TqyWv0aW5/7gbs89dcBJCqsrkPfaTMoO/Zm1HJ13dQDSqwydwSLpXDXlEV1FZoVTqQpEOv9V++Cf5AnQ==
    STRIPE_API_KEY: AgAdy6CUJubZ6M8Z57yYQOmwuYT5oBddThRSRj+r4xuyMKN5DMVTHQL6nqRvb4E1E4urLp/xqIRzfVvCpqaKSnHgjKNTVWRCJJfrVye3geFqJ1s12kpqzL2UXVMzASVr79LdEN1PpjIoeCcL+psAj31kRqlvXw2caKXK+E92QpWC7L9+EMuYbdQWI0hvih3Ebe3fM6KudCJsWuWTd12HcP+o7Bh+/KZF4Q9a/ZIivEr5u3hALRP6SpBi2TaNDTyvJuiLbY5LYOXDAjdeAylOV6niw2Qgac/N6IEEeNB3OkYNwqqAyZuZiKE0iTALQYq7b4Xpw0pl7sJx/SLZnYscRgb4m5QF9Vld8HOhBC9QfSLTMvHCG7ivP4OO8FpgXcVLbYMpVF+iDbeQMseyVzEiY/h0NUNqyaHn3AHEqz0K8HS8OwlOr837K5SSrquKxRlBljHNyMn50281/P5fl+sh9VGHjA9MvXJ19k0BXZrDqXFX/ETrfqFIYZrOWowHz9SAK1RsTmMv/06TWghEues9DwnnLOXCbZO9BHP73t8Fwdq/C4r1Bgh0/1a8tr+CpR1Xu5OYq9IIouOhEQbN/aIGRwZDSxQChpfU+wrLQiwFokiZ87I4ZZcjv32oV0SWDhvik08sAxeMAv3C0wvf0me8XkKQoc6nfH0OlQ7YgZG74js+1fAwmHQ9UVZhSuAl8n5EFZ7BtugkUkMf94NervPRWaYgdFk4R720dWqjmhDKYg==
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secrets
      namespace: payments
    type: Opaque
