name: Ledger API Secure CI

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write
  security-events: write

jobs:

  gitleaks:
    name: Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  semgrep:
    name: SAST - Semgrep
    runs-on: ubuntu-latest
    needs: gitleaks

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: |
          python -m pip install semgrep
          semgrep scan \
            --config p/python \
            --config p/security-audit \
            --sarif \
            --output semgrep.sarif \
            --error \
            ./app

      - name: Upload Semgrep SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep.sarif
          category: semgrep



  build-and-push:
    name: Build and Push Image
    needs: 
      - gitleaks
      - semgrep
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          OWNER="$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')"
          IMAGE="ghcr.io/${OWNER}/ledger-api:sha-${GITHUB_SHA::7}"

          echo "Building image: $IMAGE"


          docker build \
            -t "$IMAGE" \
            ./app

          docker push "$IMAGE"
